name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Export GITHUB_TOKEN as environment variable for the next steps
    - name: Set GitHub Token
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - run: npm ci
    - run: npm run build --if-present
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: npm test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
